// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA41q5v3vw7oqwb5meUvommmZRLn6HStS8',
    appId: '1:1046295867645:web:6b465844011b52ad4ace94',
    messagingSenderId: '1046295867645',
    projectId: 'test-d7cee',
    authDomain: 'test-d7cee.firebaseapp.com',
    storageBucket: 'test-d7cee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9dGjwXV03p3thx1w46srzLA4URwaHTD4',
    appId: '1:1046295867645:android:f10416cd2158aee64ace94',
    messagingSenderId: '1046295867645',
    projectId: 'test-d7cee',
    storageBucket: 'test-d7cee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYaCPci8R7SqSAyS8xvWkXqfYoXeXLwU8',
    appId: '1:1046295867645:ios:b62d3646d12bdeef4ace94',
    messagingSenderId: '1046295867645',
    projectId: 'test-d7cee',
    storageBucket: 'test-d7cee.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYaCPci8R7SqSAyS8xvWkXqfYoXeXLwU8',
    appId: '1:1046295867645:ios:b62d3646d12bdeef4ace94',
    messagingSenderId: '1046295867645',
    projectId: 'test-d7cee',
    storageBucket: 'test-d7cee.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );
}
